#
# This file sets up a base server.
# It should contain only the fixes required on all servers.
#
---
- name: update apt cache
  apt: update_cache=yes cache_valid_time=86400

- name: generate static key
  local_action: shell openvpn --genkey --secret files/static.key
  sudo: no

