---
- name: setup openvpn-isup
  template:
    src=templates/openvpn-isup.j2
    dest=/usr/local/bin/openvpn-isup
    owner=root
    mode=0755

- name: create sleepfile
  file: 
    dest=/var/run/openvpn-isup.sleep
    state=touch
